[project]
name = "coles-woolies-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argon2-cffi>=25.1.0",
    "fastapi>=0.141.1",
    "fastmcp>=2.3.5",
    "itsdangerous>=2.2.0",
    "psycopg[binary]>=3.3.4",
    "pydantic[email]>=2.11.4",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "requests>=2.32.3",
    "sqlalchemy>=2.0",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
